# Load the node image
FROM node:20-bookworm-slim

# Set the working directory
WORKDIR /app

COPY package.json .

# Install the dependencies
RUN npm install

# Copy the rest of the files
COPY . .

RUN npm run build

# Expose the port
EXPOSE 5173

CMD ["npm", "run", "preview", "--", "--port", "5173", "--host", "0.0.0.0"]