FROM python:3.11

WORKDIR /app

COPY . /app/

RUN pip install poetry

RUN poetry install

EXPOSE 80

CMD exec poetry run uvicorn zeno_backend.server:get_server --host 0.0.0.0 --port 80 --timeout-keep-alive 75 --workers 4
