FROM python:3.11

WORKDIR /app

COPY . /app/

RUN pip install poetry

RUN poetry install

EXPOSE 80

CMD exec poetry run uvicorn --timeout-keep-alive 75 zeno_backend.server:get_server --reload --host 0.0.0.0 --port 80
